# Created by: PwnyTail <pwnytail@chelnok.de>
# $FreeBSD$

PORTNAME=		neovim
PORTVERSION= 	${GH_TAGNAME}
DISTVERSION=	${PORTVERSION}
CATEGORIES=		editors
DISTFILES=		${PORTNAME}-${PORTVERSION}.tar.gz

MAINTAINER=	pwnytail@chelnok.de
COMMENT=	Neovim is a project that seeks to aggressively refactor Vim

LICENSE=	APACHE20

USE_GITHUB=	yes
GH_ACCOUNT=	neovim
GH_PROJECT=	neovim
GH_TAGNAME=	6139c72

DEVELOPER=yes
.include <bsd.port.mk>
